# Generated by Django 3.0.8 on 2020-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum', models.IntegerField()),
                ('ename', models.CharField(max_length=64)),
                ('esla', models.IntegerField()),
                ('eaddr', models.CharField(max_length=256)),
            ],
        ),
    ]
